finished task 11
NicholasF13/NC-News pull request #13
Opened 2023-10-05 15:21 UTC by NicholasF13

Finsished task 11 - /api/articles (topic query) endpoint

2023-10-05 15:43 UTC, NRMSMITH requested changes
A test to add and a greenlist to make 👍

2023-10-05 15:43 UTC, NRMSMITH commented on app.test.js
> +  })
Wht happens when a topic exists (paper) but it has no associated articles? (hint, it should be a 200 and just send back an empty array!)

2023-10-05 15:43 UTC, NRMSMITH commented on models/articles-model.js
> +    if (topic) {
I think we should check beforehand if the topic exists - perhaps by using a greenlist of all the topics in the database that can be updated dynamically? 😄

2023-10-06 08:52 UTC, pippaamy reviewed
great changes, go ahead and merge!

2023-10-06 08:52 UTC, pippaamy commented on app.test.js
> +  test("returns a status of 200 and an empty array if passed a topic with no associated articles", () => {
great test

2023-10-06 09:16 UTC, merged